
import "./globals.css";
/* import '@/app/ui/global.css'; */
// forma de importar Fonts en Next
import {Josefin_Sans} from 'next/font/google';

import Navbar from "../src/components/Navbar/Navbar";
import Footer from "../src/components/Footer/Footer";
/* import { Josef } from '@/app/ui/fonts'; */

/* Speed insights Vercel */
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata = {
  title: "Optimum Stucco INC",
  description: "Generated by create next app",
};

//Uso de la Font + meterla en el body como una class
const Josef = Josefin_Sans({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
})

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">

      {/* Links para el SlickSlider carrousel */}
      <head>
        <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </head>
      
      <body className={Josef.className}>

        <Navbar/> 
        {children}

        <Footer/>
        
      </body>
        {/* AL no ser el page.jsx, teniendo html, no sale al fondo, comprobar tras agregar más código. */}

      {/* antialiased es una clase tailwind, que he recreado en global.css, no sé si funciona correctamente */}
      {/* <body className={`${Josef.className} antialiased`}>{children}</body>
      */}

      
    </html>
  );
}



